version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.discord4j:discord4j-core
    versions:
    - 3.1.3
    - 3.1.4
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: io.projectreactor:reactor-test
    versions:
    - 3.4.2
    - 3.4.3
    - 3.4.4
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.5
    - 1.10.6
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
